### ISSUE TITLE
deploy the mtar file? Which Space?

### ISSUE THREAD

**Issue by draschke** [SAP/hana-shine-xsa#10]
**Documentation**
_10. Once exported, login to the XSA system via CLI and deploy the mtar file using the following command:
xs deploy com.sap.refapps.shine_1.3.x.mtar_

Sorry, for this question, but I don't know in which Space I need to deploy it?
In my DEV Space where the project is builded?

**Comment by draschke** [comment]
Deploy the mtar file

**Comment by draschke** [comment]
Tried it to deploy the mtar file in DEV and in SAP Space, but on both I get an error:
Uploading 1 files:
 T:\com.sap.refapps.shine_1.3.4.mtar
File upload finished

Starting process xs2-deploy...
Starting monitoring...
 Validating parameters...
 Processing MTA archive...
 Processing MTA extension descriptors...
 Detecting MTA major schema version...
 MTA schema version: 3.1.0
 Detecting deploy target...
 Detected deploy target "orgname DEV"
 Validating and merging descriptors...
 Detecting deployed MTA...
 No deployed MTA detected
 Collecting system parameters...
 New MTA version: 1.3.4
 Error resolving merged descriptor properties and parameters: No configuration e
ntries were found matching the filter specified in resource "sapui5-provider"
 No configuration entries were found matching the filter specified in resource "
sapui5-provider"
ERR    Error resolving merged descriptor properties and parameters: No configura
tion entries were found matching the filter specified in resource "sapui5-provid
er"
No configuration entries were found matching the filter specified in resource "s
apui5-provider"
Use "xs deploy -i 39529 -a retry" to retry the process
Use "xs deploy -i 39529 -a abort" to abort the process

**Comment by CHERIANS** [comment]
Hi,
You can deploy it in any space DEV or SAP.
Regarding the UI5 issue. This because SAPUI5 version needs to be updated in the mta.yaml as the per version which is locally available in your HANA systems. Do the below
1. Open CLI  navigate to SAP space and run command xs mtas
2. Note the version for the mta id  com.sap.ui5.dist.sapui5-dist-xsa.XSAC_UI5_FESV3 
3. One the mta.yaml and go to resources->sapui5-provider-> parameters-> version and update the version which you got in step 2 above.
4. Build the mta again and deploy
Best Regards
Stephen

**Comment by CHERIANS** [comment]
Closing issue as its resloved
