### ISSUE TITLE
[shine-cf] cannot install mtar plugin on MacOS

### ISSUE THREAD

**Issue by pfeife0** [SAP/hana-shine-xsa#13]
Hi, 

I am struggeling with the installation of the mtar plugin mentioned in the readme. 
I run the command cf install-plugin cf-cli-mta-plugin-1.0.0-darwin-x86_64.tar.gz and get this error:
fork/exec /Users/steffen/.cf/plugins/temp264374996/498008099: exec format error
File is not a valid cf CLI plugin binary.
I am running this under MacOS and have the version 6.28.0+9e024bdbd.2017-06-27 of the CF CLI installed via the PKG-installer. 
Any idea what I can do there?

Best Regards,
Steffen

**Comment by megaboy2** [comment]
Hello Steffen,

The problem was that in this version of the plugin, it was packed as tar.gz. In the tar.gz there is the installation script. So, if you want to install the plugin with that version(1.0.0) then you need first to extract the  cf-cli-mta-plugin-1.0.0-darwin-x86_64.tar.gz and then use the extracted binary to install the plugin(cf install-plugin <path-to-plugin>.

There is another option, you could install a newer version of the plugin in which you do not have to extract the tar.gz file first.
Here is how to install the latest version(1.0.2): 

1. cf uninstall-plugin MtaPlugin - this will uninstall the previous versions of the MtaPlugin
2. cf install-plugin http://nexus.wdf.sap.corp:8081/nexus/content/repositories/deploy.milestones.xmake/com/sap/golang/cf-cli-mta-plugin/1.0.2/cf-cli-mta-plugin-1.0.2-darwin.bin -f - this will install the latest plugin for Mac OS.

Bes regards,
Encho

P.S. If you want to get the version of the plugin not only for Mac OS but for Windows and Linux, you can access our github page: https://github.wdf.sap.corp/xs2ds/cf-cli-plugin

**Comment by pfeife0** [comment]
Hello Encho,

thanks for your reply, I will try it with the extracted plugin.
I am not SAP employee so I have no access to the internal links for the newer version of the plugin ;)

Best Regards,
Steffen

**Comment by megaboy2** [comment]
Hello Steffen,

The problem is that the 1.0.2 version of the cf-cli-plugin contains bug fixes which might lead to problems while you are operating with the earlier versions of the plugin. I am attaching the latest version of the plugin here in the comment. Please extract it and install the plugin :)
[cf-cli-mta-plugin-1.0.2-darwin.zip](https://github.com/SAP/hana-shine-xsa/files/1141945/cf-cli-mta-plugin-1.0.2-darwin.zip)

Best regards,
Encho

**Comment by pfeife0** [comment]
Hi Encho,

I tried it with the extracted binary and I could install the plugin. Thanks for you help.

Best Regards,
Steffen
