### ISSUE TITLE
Versions with SPS02

### ISSUE THREAD

**Issue by Lsubatin** [SAP/hana-shine-xsa#16]
Hi! Not really an issue, I see it says SPS01. I tried to create a Pull Request but was unable. I'm using HXE SPS02 and had to update the following versions for SHINE to work: 

In MTA.yaml for UI5:
   before:   version: "1.44.8"
   after:   version: "1.44.18"

In the pom.xml file, changed the gateway to 1.2.3:

before:	<sap.gateway.version>1.2.2</sap.gateway.version>
after:	<sap.gateway.version>1.2.3</sap.gateway.version>

Thanks!

Lucía.

**Comment by gouthamhanur** [comment]
thanks !
I was facing the issue with HANA Shine SPS2 due to UI5 version , After  changing it to .*18 it worked.
it was hard to identify this difference . 

goutham.

**Comment by appearmark** [comment]
Hi Lucia and Goutham,

For the UI5 version issue, it clears that, your HXE machine has XSAC_UI5_FESV3 component with version 1.44.18, and in SHINE it is tightly bound to v 1.44.8, so it fails to install and your workaround was to change the version from 1.44.8 to 1.44.18 in mta.yaml file and it works. But this is not the recommended way to do this because by changing the version in mta.yaml  you may face unstability issues in UI5 controls, you can do the other way round by upgrading/installing  XSAC_UI5_FESV3 component version to 1.44.8 , if this specific version is not installed on the machine and then install SHINE.
And for the sap gateway version issue, I am not sure exactly, @kiruthikan any comments here.

Thanks and regards,
Bismay

**Comment by bbiswal333** [comment]
Hi Lucia and Goutham,

For the UI5 version issue, it clears that, your HXE machine has XSAC_UI5_FESV3 component with version 1.44.18, and in SHINE it is tightly bound to v 1.44.8, so it fails to install and your workaround was to change the version from 1.44.8 to 1.44.18 in mta.yaml file and it works. But this is not the recommended way to do this because by changing the version in mta.yaml you may face unstability issues in UI5 controls, you can do the other way round by upgrading/installing XSAC_UI5_FESV3 component version to 1.44.8 , if this specific version is not installed on the machine and then install SHINE.
And for the sap gateway version issue, I am not sure exactly, @kiruthikan any comments here.

Thanks and regards,
Bismay

**Comment by kiruthikan** [comment]
For the sap gateway library version that is packaged with the WebIDE you are using, right click on the java module and click on "Show dependency updates". The available versions of all dependencies will be shown.
You can refer to that and change your pom accordingly.
For more details, you can refer to the troubleshooting section of the SHINE documentation.

Thanks and Regards,
Kiruthika
