### ISSUE TITLE
SAP Web IDE Full-Stack (Version: 180621) Clone request failed

### ISSUE THREAD

**Issue by bumphrey** [SAP/hana-shine-xsa#39]
Hello,
when I tried to clone the repository in SAP WebIDE Full-Stack. I receive the following error message:

"Clone request failed
Could not convert folders [shine-web, shine-site-web, shine-site-content] to modules because of an error in import process."

Whereas when I clone it in SAP Web IDE. the clone request succeeds.

**Comment by kiruthikan** [comment]
Hi,

Kindly use SAP WebIDE for SAP HANA for deploying and running SHINE.

Thanks and Regards,
Kiruthika

**Comment by JamiVaraPrasad** [comment]
Hi Kiruthikan,
Could you please help me with a repository (from shine) which supports SAP WebIDE Full-Stack.
Regards
Jami

**Comment by kiruthikan** [comment]
Hello Jami,

Currently FullStack WebIDE doesn’t fully support some features available in SAP WebIDE for SAP Hana. 
It will be available in near future. But,as of now, you would have to use SAP WebIDE for SAP Hana to deploy SHINE in XSA.
You could try installing a HANA Express edition System and use the WebIDE in that.
To understand more, Could you tell me weather you want to deploy the application on XSA or on SAP Cloud Foundry? 

Thanks and Regards,
Kiruthika

**Comment by pbrose** [comment]
This was very helpful in finding out my issue when I had the same error message turns out my module type in the mta.yaml was `type: javascript.nodejs`. WebIDE doesn't support that type so I had to change it to `type: nodejs`. This was a very hard error to find - it would be helpful if the error message was a bit more specific.
