### ISSUE TITLE
Errors on master version

### ISSUE THREAD

**Issue by MeitalKalaf** [SAP/hana-shine-xsa#54]
There are some error with the master version:
1. The modules file content is not align with the existing modules in the project (e.g. Java module is not exist in this version, but it still display in the module file)
2. When building the MTA project I get an error:
[ERROR] Module shine-site-web does not exist in the folder site-web/.
1:41:23 PM (Builder) Build of /hana-shine-xsa failed.
3. I can't import the project if I download it and import it to Web IDE. 
Please check
Thanks,
Meital

**Comment by bbiswal333** [comment]
Hi Meital,

Thanks for reporting these errors.

1.  The modules name is fixed in module file.
2.  Build error in site-content and site-web is fixed. 
3.  Generally, if you download the zip from GitHub, when you extract the zip you will find the folder structure something like  **hana-shine-xsa-master** -> **hana-shine-xsa-master** -> **<project_content>**. This is the way how GitHub zip up the project. 
After importing into the Web IDE, just delete the .che and mta.yaml file created by WebIde in the root folder and move the content from sub project folder to the root folder and delete that sub project folder.
It is recommended to fork the project to your repo and clone the project into the Web IDE.

Thanks,
Bismay

**Comment by MeitalKalaf** [comment]
Thank you
